### ISSUE TITLE
nightscout-ps1 process never completes

### ISSUE THREAD

**Issue by rarneson** [TooTallNate/nightscout-ps1#1]
`nightscout-ps1 -n <my url> -c ~/.nightscout-ps1.env` never actually exits. While it's running, the bg values are updated but as soon as I `ctrl+c` it stops.

Maybe I'm not understanding the installation and usage correctly. It seems that installation is via `npm install` (or Github releases), then usage is via `nightscout-ps1`. However, just below that are instructions on registering the binary with launchctl which requires one to clone the repo. Am I right in assuming that the usage by running the `nightscout-ps1` binary is for running it in the foreground while registering it as a service is what will keep it running at all times?

**Comment by TooTallNate** [comment]
Hey there @rarneson, glad to see that you're interested in using my little project! Clearly the setup instructions could use some improvements (PR welcome).

So yes, all your assumptions are correct here. The `nightscout-ps1` program runs in the foreground and to have it running at all times it is recommended to set it up as a service via your operating system.

You _shouldn't_ really have to clone the repo in order to set up the service. The service definition is just a single file (https://raw.githubusercontent.com/TooTallNate/nightscout-ps1/master/service/nightscout-ps1.service), so we could tweak the instructions to download via `curl` or something easier than cloning.

Let me know if you get the service all set up and running, and if I can improve the installation instructions in any way for the future. Thanks!

**Comment by rarneson** [comment]
Absolutely, thanks for the response! I'll tinker with it and see if I can get the service working without needing anything cloned locally. If so, I can work on a PR to update the documentation.
